version: "3"
services:
  client:
    build:
      context: ./client/
      dockerfile: .docker/Dockerfile
    ports:
      - 3000:3000
    networks:
      - recipes-app-network
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    stdin_open: true
    depends_on: 
      - api
    tty: true

  api:
    build:
      context: ./server
      dockerfile: .docker/Dockerfile
    ports:
      - 3001:3001
    networks:
      - recipes-app-network
    volumes:
      - ./server/src:/usr/app/src
    depends_on:
      - db

  db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - recipes-app-network
    env_file: ./server/.env
    restart: always
    volumes:
      - mongo-data:/data/db

networks:
  recipes-app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local